### ISSUE TITLE
프로젝트 초기 세팅

### ISSUE THREAD

**Issue by choi2601** [Team-Raon/jibro-frontend#1]
## 설명
- 프로젝트 초기 세팅

## todos
 - [x] 폴더 구조 생성
 - [x] redux-toolkit 세팅
 - [x] react-query 세팅
 - [x] navigation 세팅 
 - [x] 전역 경로 설정
