### ISSUE TITLE
사용자 권한 설정

### ISSUE THREAD

**Issue by choi2601** [Team-Raon/jibro-frontend#7]
## 설명
- 권한 설정

## todos
 - [x] 권한 설정 custom hooks 구현
 - [x] ios 권한 설정 세팅
 - [x] 안드로이드 권한 설정 세팅
